// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc293.FRC_HelloWorld.subsystems;


import org.usfirst.frc293.FRC_HelloWorld.Robot;
import org.usfirst.frc293.FRC_HelloWorld.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Motors extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX talonLeft;
    private WPI_TalonSRX talonRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    ////Motors Constants
    private final float LEFT_DEADZONE = -0.25f;
    private final float RIGHT_DEADZONE = 0.25f;
    ////

    public Motors() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        talonLeft = new WPI_TalonSRX(16);
        
        
        
        talonRight = new WPI_TalonSRX(17);
        
        
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        float gSensorY = Robot.sensors.getGSensorYValue(); //Get G Sensor Y axis vlaue

        ////Adjust motor speeds depending on G sensors
        //if sensor is negative rotate robot left else rotate right
        if(gSensorY < LEFT_DEADZONE ) { //Rotate left
            System.out.println("Rotating left at " + Math.abs(gSensorY));
            talonRight.set(0);
            talonLeft.set(Math.abs(gSensorY));
        } else if(gSensorY > RIGHT_DEADZONE ) { //Rotate right
            System.out.println("Rotating right at " + Math.abs(gSensorY));
            talonRight.set(Math.abs(gSensorY));
            talonLeft.set(0);
        } else { //Sensor is in deadzone, turn off motors
            talonLeft.set(0);
            talonRight.set(0);
        }
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

